name: iOS-Release

on:
  repository_dispatch:
    types: [update]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: repo_src
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: c4dt/arti-rest

      - name: update file
        run: |
          export XCFRAMEWORK_URL=https://github.com/c4dt/arti-rest/releases/download/${{ steps.repo_src.outputs.release }}/arti-rest.xcframework.zip
          wget $XCFRAMEWORK_URL
          export CHK=$( sha256sum arti-rest.xcframework.zip | sed -e 's/ .*//' )
          echo "Checksum is: $CHK"
          sed -i -e "s=\(\\s*url: \).* \(// XCFramework URL.*\)=\1\"$XCFRAMEWORK_URL\", \2=" Package.swift
          sed -i -e "s=\(\\s*checksum: \).* \(// XCFramework checksum.*\)=\1\"$CHK\" \2=" Package.swift
          cat Package.swift

      - uses: EndBug/add-and-commit@v7
        with:
          add: 'Package.swift'
          tag: ${{ steps.repo_src.outputs.release }}

